### ISSUE TITLE
"make check" fails for provided Libint 2.6.0 source tarballs

### ISSUE THREAD

**Issue by boegel** [cp2k/libint-cp2k#1]
I tried running "`make check`"  after configuring with `./configure --prefix /tmp/ --enable-fortran` and building with `make -j 9`, but I ran into problems like:

```
../../include/libint2/./engine.impl.h:627:3: note: suggested alternative: LIBINT2_MAX_AM_default
../../include/libint2/./engine.impl.h:627:3: error: LIBINT2_MAX_AM_default1 was not declared in this scope
   BOOST_PP_LIST_FOR_EACH_PRODUCT(
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The same problem occurs with multiple tarballs (I tried  `libint-v2.6.0-cp2k-lmax-4.tgz` and `libint-v2.6.0-cp2k-lmax-7.tgz`).

There's a fix for this issue that was merged via https://github.com/evaleev/libint/pull/149, but this requiring re-doing the "`make export`"... Is there a way to run the tests with the source tarballs provided here?

If I apply the fix from https://github.com/evaleev/libint/pull/149 to the original Libint 2.6.0 sources, configure as done in https://github.com/cp2k/libint-cp2k/blob/ef735457fb1693fb156019b6f9c8c22968f08b4c/Jenkinsfile#L55, run "`make export`" and then rerun the `configure`/`make`/`make install` cycle using the obtained source tarball, things seem to be working as expected (`make check` passes without problems).

**Comment by pseewald** [comment]
Sorry, this issue was unnoticed. Since this bug was fixed in libint, there are no longer any problems with newer release of libint-cp2k, I think. I close this but feel free to reopen if this issue remains.

**Comment by boegel** [comment]
@pseewald Do you have a pointer to the fix in Libint?

**Comment by boegel** [comment]
Ah, nevermind, I pointed to the fix myself... 🤦  (https://github.com/evaleev/libint/pull/149)

Thanks for following up!

**Comment by mbanck** [comment]
Well, it's still a problem with the 2.6.0 libint-cp2k, it's a bit unfortunate that libint upstream does not seem to think this is worth issuing a 2.6.1 for. Could this be patched in the Jenkinsfile for libint-cp2k?
