### ISSUE TITLE
The section "Build instructions" is USELESS

### ISSUE THREAD

**Issue by qbit19** [cp2k/libint-cp2k#4]
Hello team,

I would like to point out that the section "Build instructions" points to external link : https://github.com/evaleev/libint/wiki#compiling-libint-library where only dysfunctional CMAKE is discussed: "As of version 2.6.0 the Autoconf build is deprecated; the exported libint library should be configured with CMake and built with any CMake-supported generator, e.g. Ninja and GNU Make. Only CMake-based build will be discussed."

What is important for cross-compiling on supercomputer Fugaku is using the ./configure with flags because cmake does not recognize Fujitsu CXX compiler ??
In particular, I am able to cross-compile libraries on Fugaku using this basic code:
./configure CC=mpifccpx CXX=mpiFCCpx FC=mpifrtpx LD=mpifrtpx --build=x86_64-pc-linux-gnu --host=arm-64fx-linux-gnu --target=arm-64fx-linux-gnu
Of course, I add also lines for CFLAGS, CXXFLAGS, FCFLAGS, LDFLAGS, but the main point is that I am able to specify "build", "host" and "target". With cmake, there is no way that I do the cross-compilation because the Fujitsu compiler is not recognized and there is no support.

I think that it would be great if you add to your  "Build instructions"  a basic outline of how to use the mantra:
./configure
make
make install

In particular, when compiling CP2K I get error with libint_wrapper
From i have found in forums online is that maybe the Fortran binding is not working. Where exactly in the above ./configure workflow I am supposed to do Fortran binding?

**Comment by dev-zero** [comment]
This is how we do it in the CP2K toolchain:

https://github.com/cp2k/cp2k/blob/08c05a7d6279fafeef45cafb7a5aedea4c936a6d/tools/toolchain/scripts/stage3/install_libint.sh#L82-L87
